// Auto-generated by scripts/upload-shopify-file.ts.
// Re-run the script with --replace to update a constant.
//
// Until the upload script has been run, these are local fallbacks. The
// <link rel="preload"> in app/root.tsx and the hero <img> in
// app/views/home/HomeView.tsx will use the local /assets/* file as a
// fallback when a URL is missing (i.e. an empty string), and switch to
// the Shopify CDN URL once populated.

export const heroImage = '/assets/hero-portrait.jpg';
export const heroImage800 = '/assets/hero-portrait-800.jpg';
