export type Shade = { code: string; hex: string; family: string };

export const SHADES: Shade[] = [
    { code: "1-LL", hex: "#F7F2DC", family: "Cream" },
    { code: "1-L", hex: "#F2EAC5", family: "Light Cream" },
    { code: "1", hex: "#F0E0A0", family: "Pale Yellow" },
    { code: "2", hex: "#EDD576", family: "Yellow" },
    { code: "3", hex: "#E8CC50", family: "Golden Yellow" },
    { code: "4", hex: "#E0C02E", family: "Yellow Gold" },
    { code: "5", hex: "#D4B228", family: "Deep Gold" },
    { code: "6", hex: "#C4B22A", family: "Olive Yellow" },
    { code: "7", hex: "#B8B838", family: "Yellow Green" },
    { code: "8", hex: "#A0C24E", family: "Light Green" },
    { code: "9", hex: "#82B342", family: "Green" },
    { code: "10", hex: "#5FA23D", family: "Medium Green" },
    { code: "11", hex: "#418C3A", family: "Green" },
    { code: "11-D", hex: "#2D6E2E", family: "Dark Green" },
    { code: "12", hex: "#1F5E28", family: "Dark Green" },
    { code: "13", hex: "#1A4C22", family: "Deep Green" },
    { code: "14-L", hex: "#92AC7A", family: "Light Sage" },
    { code: "14", hex: "#7E9A6A", family: "Sage" },
    { code: "15", hex: "#6C8A52", family: "Olive Green" },
    { code: "16", hex: "#4B5E30", family: "Dark Olive" },
    { code: "17", hex: "#1F4C28", family: "Dark Green" },
    { code: "17-D", hex: "#12341A", family: "Very Dark Green" },
    { code: "18-LL", hex: "#F6DEEA", family: "Pale Pink" },
    { code: "18-L", hex: "#F0CADE", family: "Light Pink" },
    { code: "18", hex: "#EAAACE", family: "Pink" },
    { code: "19", hex: "#EA92BE", family: "Pink" },
    { code: "20", hex: "#E272AA", family: "Rose Pink" },
    { code: "21", hex: "#DA467E", family: "Deep Pink" },
    { code: "22", hex: "#DA2A52", family: "Red Pink" },
    { code: "23", hex: "#D22032", family: "Red" },
    { code: "24", hex: "#CA1A22", family: "Red" },
    { code: "25", hex: "#B2121A", family: "Dark Red" },
    { code: "26", hex: "#9A121A", family: "Dark Red" },
    { code: "27", hex: "#7A1222", family: "Maroon" },
    { code: "28-L", hex: "#EDE6F0", family: "Pale Lavender" },
    { code: "28", hex: "#EAE2EE", family: "Off White/Lavender" },
    { code: "29", hex: "#CABAE2", family: "Light Purple" },
    { code: "30", hex: "#AA92D2", family: "Purple" },
    { code: "31", hex: "#8A6AC2", family: "Purple" },
    { code: "31-D", hex: "#5A42A2", family: "Dark Purple" },
    { code: "32-LL", hex: "#EAEAEA", family: "Pale Grey" },
    { code: "32-L", hex: "#D2D2D2", family: "Light Grey" },
    { code: "32", hex: "#AAAAAA", family: "Grey" },
    { code: "33", hex: "#6A6A6A", family: "Dark Grey" },
    { code: "34", hex: "#4A4A52", family: "Charcoal" },
    { code: "35", hex: "#DACAEA", family: "Pale Lilac" },
    { code: "36", hex: "#BA9ADA", family: "Light Purple" },
    { code: "37", hex: "#9A6ACA", family: "Purple" },
    { code: "38", hex: "#8252C2", family: "Purple" },
    { code: "39", hex: "#6A3AB2", family: "Deep Purple" },
    { code: "40", hex: "#5A2AA2", family: "Dark Purple" },
    { code: "41", hex: "#4A2292", family: "Indigo" },
    { code: "42", hex: "#3A1A7A", family: "Dark Indigo" },
    { code: "42-D", hex: "#2A125A", family: "Very Dark Purple" },
    { code: "43-L", hex: "#E2C2DA", family: "Pale Mauve" },
    { code: "43", hex: "#CA8ABA", family: "Mauve Pink" },
    { code: "44", hex: "#BA6AA2", family: "Magenta Pink" },
    { code: "45", hex: "#AA5292", family: "Magenta" },
    { code: "46", hex: "#9A3A7A", family: "Deep Magenta" },
    { code: "47", hex: "#822A62", family: "Dark Magenta" },
    { code: "47-D", hex: "#621A4A", family: "Dark Maroon Purple" },
    { code: "48-LL", hex: "#DAEAF2", family: "Pale Blue" },
    { code: "48-L", hex: "#BADAEA", family: "Light Blue" },
    { code: "48", hex: "#92C2DE", family: "Blue" },
    { code: "49", hex: "#62AAD2", family: "Blue" },
    { code: "50", hex: "#3A8AC2", family: "Medium Blue" },
    { code: "51", hex: "#2A72B2", family: "Blue" },
    { code: "52", hex: "#1A5AA2", family: "Royal Blue" },
    { code: "53", hex: "#124A92", family: "Dark Blue" },
    { code: "54", hex: "#0E3A7A", family: "Navy" },
    { code: "54-D", hex: "#0A2A62", family: "Dark Navy" },
    { code: "54-DD", hex: "#061A42", family: "Very Dark Navy" },
    { code: "55-LL", hex: "#FAF6EA", family: "Off White" },
    { code: "55-L", hex: "#F2EAD2", family: "Cream" },
    { code: "55", hex: "#F2DAA2", family: "Light Gold" },
    { code: "56", hex: "#F2CA6A", family: "Gold" },
    { code: "57", hex: "#F2BA42", family: "Gold Yellow" },
    { code: "58", hex: "#F2AA2A", family: "Orange Gold" },
    { code: "59", hex: "#F29A1A", family: "Orange" },
    { code: "60", hex: "#EA8A0A", family: "Deep Orange" },
    { code: "61", hex: "#F28A2A", family: "Orange" },
    { code: "62", hex: "#EA6A1A", family: "Deep Orange" },
    { code: "62-D", hex: "#D2520A", family: "Dark Orange" },
    { code: "63-L", hex: "#CADEE2", family: "Pale Blue" },
    { code: "63", hex: "#AACEDA", family: "Light Blue" },
    { code: "64", hex: "#82BACE", family: "Blue" },
    { code: "65", hex: "#529AB2", family: "Teal Blue" },
    { code: "66", hex: "#428AAA", family: "Blue" },
    { code: "67", hex: "#326A92", family: "Dark Blue" },
    { code: "68", hex: "#225272", family: "Navy Blue" },
    { code: "69", hex: "#1A425A", family: "Dark Navy" },
    { code: "70", hex: "#12324A", family: "Navy" },
    { code: "70-D", hex: "#0C263A", family: "Very Dark Navy" },
    { code: "70-DD", hex: "#081A2A", family: "Darkest Navy" },
    { code: "71-LL", hex: "#CAEEEA", family: "Pale Turquoise" },
    { code: "71-L", hex: "#92DAD2", family: "Turquoise" },
    { code: "71", hex: "#5AC2BA", family: "Turquoise" },
    { code: "72", hex: "#3AAAA2", family: "Teal" },
    { code: "73-L", hex: "#FADEC2", family: "Pale Peach" },
    { code: "73", hex: "#F2CAA2", family: "Peach" },
    { code: "74", hex: "#F2924A", family: "Orange" },
    { code: "75", hex: "#EA7A3A", family: "Orange" },
    { code: "76", hex: "#E26232", family: "Orange Red" },
    { code: "77", hex: "#DA5232", family: "Red Orange" },
    { code: "78", hex: "#CA422A", family: "Deep Red Orange" },
    { code: "79-L", hex: "#F2C2B2", family: "Pale Coral" },
    { code: "79", hex: "#EAA292", family: "Coral" },
    { code: "80", hex: "#E28272", family: "Salmon" },
    { code: "81", hex: "#DA6A52", family: "Red Orange" },
    { code: "82", hex: "#D25A42", family: "Red" },
    { code: "83", hex: "#CA4A3A", family: "Red" },
    { code: "84", hex: "#BA3A2A", family: "Deep Red" },
    { code: "85", hex: "#7ABADA", family: "Light Blue" },
    { code: "86", hex: "#529ACA", family: "Blue" },
    { code: "87", hex: "#3A7AB2", family: "Blue" },
    { code: "88", hex: "#224A7A", family: "Navy" },
    { code: "89", hex: "#162A5A", family: "Dark Navy" },
    { code: "90-L", hex: "#0E1A4A", family: "Navy" },
    { code: "90", hex: "#0A123A", family: "Dark Navy" },
    { code: "90-D", hex: "#060A22", family: "Darkest Navy" },
    { code: "91-LL", hex: "#CAEADE", family: "Pale Mint" },
    { code: "91-L", hex: "#A2DACA", family: "Mint" },
    { code: "91", hex: "#72C2AA", family: "Teal Green" },
    { code: "92", hex: "#4AAA8A", family: "Green Teal" },
    { code: "93", hex: "#328A6A", family: "Dark Teal" },
    { code: "94", hex: "#226A52", family: "Deep Teal" },
    { code: "95", hex: "#F2A2AA", family: "Pink" },
    { code: "96", hex: "#EA8A92", family: "Pink" },
    { code: "97", hex: "#E2727A", family: "Red Pink" },
    { code: "98", hex: "#DA5A62", family: "Red" },
    { code: "99", hex: "#CA424A", family: "Deep Red" },
    { code: "100", hex: "#B2323A", family: "Dark Red" },
    { code: "100-D", hex: "#9A3242", family: "Darker Red" },
    { code: "101-LL", hex: "#DAF2EA", family: "Pale Mint" },
    { code: "101-L", hex: "#BAEADA", family: "Mint" },
    { code: "101", hex: "#92DAC2", family: "Teal" },
    { code: "102", hex: "#6ACAAA", family: "Teal Green" },
    { code: "103", hex: "#42B292", family: "Green" },
    { code: "104", hex: "#2A9A7A", family: "Dark Teal Green" },
    { code: "105", hex: "#1A7A62", family: "Deep Teal" },
    { code: "108-L", hex: "#E2CAA2", family: "Tan" },
    { code: "108", hex: "#CAAA7A", family: "Brown Tan" },
    { code: "108-D", hex: "#AA8A5A", family: "Dark Tan" },
    { code: "109-LL", hex: "#EADABA", family: "Pale Tan" },
    { code: "109-L", hex: "#DAC29A", family: "Light Tan" },
    { code: "109", hex: "#C2A272", family: "Tan" },
    { code: "110", hex: "#AA8252", family: "Brown" },
    { code: "111", hex: "#926A3A", family: "Brown" },
    { code: "112", hex: "#7A522A", family: "Dark Brown" },
    { code: "112-D", hex: "#623A1A", family: "Darkest Brown" },
    { code: "113", hex: "#F2DAC2", family: "Pale Peach" },
    { code: "114-L", hex: "#EAC2A2", family: "Peach" },
    { code: "114", hex: "#E2AA7A", family: "Orange Peach" },
    { code: "115", hex: "#DA925A", family: "Salmon Orange" },
    { code: "116", hex: "#D27A42", family: "Orange" },
    { code: "117", hex: "#CA6232", family: "Orange Red" },
    { code: "118", hex: "#C2522A", family: "Red Orange" },
    { code: "119", hex: "#BA4222", family: "Deep Red Orange" },
    { code: "120", hex: "#AA3A1A", family: "Dark Red" },
    { code: "120-D", hex: "#9A3212", family: "Darkest Red" },
    { code: "138", hex: "#B2822A", family: "Mustard Gold" },
    { code: "139", hex: "#C29A3A", family: "Gold" },
    { code: "139-D", hex: "#9A7A22", family: "Dark Gold" },
    { code: "140", hex: "#DAAA3A", family: "Golden Yellow" },
    { code: "141", hex: "#E2B252", family: "Gold" },
    { code: "142", hex: "#E2BA5A", family: "Gold" },
    { code: "143", hex: "#E2C272", family: "Light Gold" },
    { code: "144", hex: "#EACA82", family: "Pale Gold" },
    { code: "145", hex: "#C29ADA", family: "Lilac Purple" },
    { code: "146", hex: "#A272C2", family: "Purple" },
    { code: "147", hex: "#8252A2", family: "Deep Purple" },
    { code: "147-D", hex: "#6A3A8A", family: "Dark Purple" },
    { code: "148", hex: "#E2822A", family: "Orange" },
    { code: "149", hex: "#C2CA6A", family: "Yellow Green" },
    { code: "150", hex: "#AABA52", family: "Olive Green" },
    { code: "151", hex: "#92AA3A", family: "Green" },
    { code: "152", hex: "#7A9A2A", family: "Dark Olive Green" },
    { code: "153-L", hex: "#E2BA92", family: "Pale Peach Tan" },
    { code: "153", hex: "#DAA272", family: "Peach Tan" },
    { code: "154", hex: "#D28A5A", family: "Terracotta" },
    { code: "155", hex: "#C25A3A", family: "Rust Red" },
    { code: "156", hex: "#D2A292", family: "Dusty Rose" },
    { code: "157-LL", hex: "#DAB2A2", family: "Pale Rose Tan" },
    { code: "157-L", hex: "#C29282", family: "Rose Tan" },
    { code: "157", hex: "#A2725A", family: "Brown Rose" },
    { code: "158", hex: "#C2AA52", family: "Olive Gold" },
    { code: "158-D", hex: "#A2922A", family: "Dark Olive Gold" },
    { code: "159", hex: "#DAAA3A", family: "Golden Yellow" },
    { code: "160", hex: "#EACA82", family: "Light Gold" },
    { code: "161", hex: "#F2DA9A", family: "Pale Gold" },
    { code: "162", hex: "#F2E2B2", family: "Very Pale Gold" },
    { code: "163-LL", hex: "#DACA5A", family: "Olive Yellow" },
    { code: "163-L", hex: "#C2B242", family: "Olive Gold" },
    { code: "164", hex: "#AA9A2A", family: "Dark Olive Gold" },
    { code: "165", hex: "#928222", family: "Olive Brown" },
    { code: "166", hex: "#7A6A1A", family: "Dark Olive Brown" },
    { code: "167", hex: "#6A5A12", family: "Deep Olive Brown" },
    { code: "168", hex: "#5A4A0A", family: "Dark Bronze" },
    { code: "169", hex: "#4A3A0A", family: "Darkest Bronze" },
    { code: "170-LL", hex: "#DAEAE2", family: "Pale Seafoam" },
    { code: "170-L", hex: "#A2CAB2", family: "Seafoam" },
    { code: "170", hex: "#7AAA92", family: "Sage Green" },
    { code: "171", hex: "#5A9272", family: "Green" },
    { code: "172", hex: "#3A7A52", family: "Dark Green" },
    { code: "173", hex: "#F2CA8A", family: "Light Peach Gold" },
    { code: "174", hex: "#EAB272", family: "Peach Gold" },
    { code: "175-LL", hex: "#F2E2C2", family: "Pale Cream Gold" },
    { code: "175-L", hex: "#EACA9A", family: "Light Tan Gold" },
    { code: "175", hex: "#E2B272", family: "Tan Gold" },
    { code: "175-D", hex: "#CA9A52", family: "Dark Tan Gold" },
    { code: "176", hex: "#C28242", family: "Rust Tan" },
    { code: "177", hex: "#BA6A32", family: "Rust" },
    { code: "178", hex: "#B25A2A", family: "Dark Rust" },
    { code: "179", hex: "#DA5242", family: "Red Orange" },
    { code: "180", hex: "#CA3A32", family: "Red" },
    { code: "180-D", hex: "#B2322A", family: "Dark Red" },
    { code: "181", hex: "#C2CAC2", family: "Pale Grey Green" },
    { code: "182", hex: "#AA3A32", family: "Deep Red" },
    { code: "184-L", hex: "#AADAEA", family: "Light Sky Blue" },
    { code: "184", hex: "#82CADA", family: "Sky Blue" },
    { code: "185", hex: "#6ABACA", family: "Blue" },
    { code: "186", hex: "#3A9ABA", family: "Deep Sky Blue" },
    { code: "187", hex: "#EACA5A", family: "Yellow Gold" },
    { code: "188", hex: "#E2B23A", family: "Gold" },
    { code: "189", hex: "#F2C2CA", family: "Pale Pink" },
    { code: "190", hex: "#EAAAB2", family: "Light Pink" },
    { code: "191", hex: "#E29AA2", family: "Pink" },
    { code: "192", hex: "#CA5A72", family: "Rose Red" },
    { code: "193", hex: "#BA3A52", family: "Deep Rose" },
    { code: "194", hex: "#B22A42", family: "Dark Rose Red" },
    { code: "195", hex: "#F2C292", family: "Light Peach" },
    { code: "196", hex: "#EAAA6A", family: "Peach Orange" },
    { code: "197", hex: "#F2AABA", family: "Pink" },
    { code: "199", hex: "#EA82A2", family: "Deep Pink" },
    { code: "201", hex: "#E25A92", family: "Magenta Pink" },
    { code: "202", hex: "#D2427A", family: "Deep Magenta" },
    { code: "202-D", hex: "#C22A62", family: "Dark Magenta" },
    { code: "203", hex: "#CA2232", family: "Red" },
    { code: "206", hex: "#8A222A", family: "Dark Maroon Red" },
    { code: "210", hex: "#C25232", family: "Rust Red" },
    { code: "212", hex: "#C26A42", family: "Rust Orange" },
    { code: "213", hex: "#6A5A32", family: "Olive Brown" },
    { code: "214", hex: "#F2DAE2", family: "Pale Pink" },
    { code: "215-LL", hex: "#F2C2D2", family: "Pale Rose Pink" },
    { code: "215", hex: "#EAAABA", family: "Rose Pink" },
    { code: "216", hex: "#E292AA", family: "Deep Rose Pink" },
    { code: "217", hex: "#A2B252", family: "Olive Green" },
    { code: "218", hex: "#829A3A", family: "Green" },
    { code: "218-D", hex: "#6A8222", family: "Dark Olive Green" },
    { code: "219", hex: "#6ACAB2", family: "Teal Green" },
    { code: "220", hex: "#A29262", family: "Tan Olive" },
    { code: "221", hex: "#AA8A72", family: "Taupe" },
    { code: "222", hex: "#C2AA92", family: "Light Taupe" },
    { code: "223", hex: "#E2CAB2", family: "Pale Tan" },
    { code: "224", hex: "#C2C2A2", family: "Sage Tan" },
    { code: "225", hex: "#DACAB2", family: "Light Tan" },
    { code: "225-D", hex: "#C2AA92", family: "Tan" },
    { code: "226-LL", hex: "#DAEADA", family: "Pale Mint Green" },
    { code: "226-L", hex: "#C2DAC2", family: "Light Mint Green" },
    { code: "226", hex: "#AACAAA", family: "Mint Green" },
    { code: "227", hex: "#B2E2C2", family: "Pale Green" },
    { code: "228", hex: "#92DAB2", family: "Light Green" },
    { code: "229", hex: "#6A3A32", family: "Dark Brown Red" },
    { code: "230", hex: "#7A4A3A", family: "Brown" },
    { code: "231", hex: "#5A2A22", family: "Dark Brown" },
    { code: "232", hex: "#C2AA82", family: "Tan" },
    { code: "233", hex: "#C29A62", family: "Golden Tan" },
    { code: "234-L", hex: "#D2B26A", family: "Light Mustard" },
    { code: "234", hex: "#B29A4A", family: "Mustard" },
    { code: "235", hex: "#C2A272", family: "Tan Gold" },
    { code: "236", hex: "#B29A6A", family: "Khaki Tan" },
    { code: "237", hex: "#DAC2A2", family: "Pale Tan" },
    { code: "238", hex: "#C2AA82", family: "Tan" },
    { code: "239", hex: "#B2925A", family: "Dark Tan" },
    { code: "240-L", hex: "#D2C29A", family: "Pale Khaki" },
    { code: "240", hex: "#C2AA72", family: "Khaki" },
    { code: "241", hex: "#DAC292", family: "Light Khaki Gold" },
    { code: "242", hex: "#C2925A", family: "Terracotta Tan" },
    { code: "242-D", hex: "#B2222A", family: "Dark Red" },
  ];